name: CI/CD Pipeline
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Test Image
        run: docker build -t vikas9dev/docker-react -f Dockerfile.dev .

      - name: Run Tests
        run: docker run -e CI=true vikas9dev/docker-react npm run test -- --coverage

      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Build and Push Production Docker Image
        if: github.ref == 'refs/heads/main'
        run: |
          docker build -t vikas9dev/docker-react -f Dockerfile .
          docker push vikas9dev/docker-react
  
  deploy:
    needs: test # Only deploy if tests pass
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate Deployment Package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EBS
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: docker-react
          environment_name: Docker-react-env 
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
